version: '3.4'
services:

  db:
    image: postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
    ports:
      - 5432:5432
    container_name: serial-vault-database

  web:
    image: serial-vault-web
    depends_on:
      - db
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - API_KEY=${API_KEY}
      - KEYSTORE_SECRET=${KEYSTORE_SECRET}
    ports:
      - "8080:8080"
      - "8081:8081"
    container_name: serial-vault-web-container